version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.7.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0-beta.1
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
  resource:
    image: semtech/mu-cl-resources:1.19.0
    links:
      - database:database
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      # LOG_OUTGOING_SPARQL_QUERIES: "true"
      # INSPECT_OUTGOING_SPARQL_QUERIES: "false"
      # LOG_INCOMING_SPARQL_QUERIES: "true"
      # INSPECT_INCOMING_SPARQL_QUERIES: "false"
      # LOG_ACCESS_RIGHTS: "true"
      # INSPECT_ACCESS_RIGHTS_PROCESSING: "true"
      # LOG_DELTA_MESSAGES: "true"
      # LOG_DELTA_CLIENT_COMMUNICATION: "true"
      # LOG_TEMPLATE_MATCHER_PERFORMANCE: "false"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "on"
      # LOG_DATABASE_OVERLOAD_TICK: "on"
    volumes:
      - ./config/authorization:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
        - ./config/delta:/config
  migration:
    image: semtech/mu-migrations-service:0.5.1
    volumes:
      - ./config/migrations:/data/migrations
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
